const darkTheme = {
    bodyHero: "var(--clr-black)",
    colorHero: "var(--clr-primary-variant)",
    bgherobtn: "var(--clr-primary-dm)",
    colorherobtn: "var(--clr-white)",
    bgherobtnhover: "var(--clr-primary-variant)",
    navlinkscolor: "var(--clr-grey-5)",
    colorlogohero: "var(--clr-primary-variant)",
    navbar: "var(--clr-primary-dm)",
    navbar2: "var(--clr-black)",
    namenavbar: "var(--clr-white)",
    aboutbg: "var(--clr-black)",
    titleAbout: "var(--clr-primary-variant)",
    bgtimeline: "var(--clr-black)",
    timelinetitle: "var(--clr-primary-variant)",
    cardtimeline: "var(--clr-primary-dm)",
    titletimeline: "#03DAC6",
    texttimeline: "var(--clr-grey-5)",
    bgportfoloio: "var(--clr-black)",
    titleportfolio: "var(--clr-primary-variant)",
    bgbtnproyects: "var(--clr-primary-variant)",
    colorbntproyects: "var(--clr-primary-dm)",
    activebtnprotects: "var(--clr-primary-dm)",
    bgcardproyects: "var(--clr-primary-dm)",
    btngitproyect: "var(--clr-primary-variant)",
    btncolorgitproyect: "var(--clr-primary-1)",
    bgform: "var(--clr-black)",
    titleform: "var(--clr-primary-variant)",
    labelform: "var(--clr-primary-variant)",
    inputs: "var(--clr-grey-2)",
    colorinputs: "var(--clr-grey-7)",
    sidebar: "var(--clr-primary-variant)",
    sidebarmenu: "var(--clr-black)",
    btnclose: "var(--clr-primary-dm)",
    brndark: "var(--clr-primary-dm)",
    colorsvgdard: "var(--clr-white)"
}

const lgTheme = {
    bodyHero: "var(--clr-primary-9)",
    colorHero: "var(--clr-primary-2)",
    bgherobtn: "var(--clr-primary-5)",
    colorherobtn: "var(--clr-primary-1)",
    bgherobtnhover: "var(--clr-primary-9)",
    colorlogohero: "var(--clr-primary-1)",
    navbar: "var(--clr-white)",
    navbar2: "var(--clr-primary-10)",
    namenavbar: "var(--clr-primary-1)",
    aboutbg: "var(--clr-white)",
    titleAbout: "var(--clr-primary-2)",
    bgtimeline: "var(--clr-primary-9)",
    timelinetitle: "var(--clr-primary-2)",
    cardtimeline: "var(--clr-primary-7)",
    titletimeline: "var(--clr-white)",
    texttimeline: "var(--clr-grey-2)",
    bgportfoloio: "var(--clr-white)",
    navlinkscolor: "var(--clr-grey-3)",
    titleportfolio: "var(--clr-primary-2)",
    bgbtnproyects: "var(--clr-grey-9)",
    colorbntproyects: "var(--clr-primary-5)",
    activebtnprotects: "var(--clr-primary-7)",
    bgcardproyects: "var(--clr-primary-9)",
    btngitproyect: "#FEB139",
    btncolorgitproyect: "var(--clr-white)",
    bgform: "var(--clr-primary-9)",
    titleform:  "var(--clr-primary-2)",
    labelform: "var(--clr-primary-5)",
    inputs: "var(--clr-white)",
    colorinputs: "var(--clr-black)",
    sidebar: "var(--clr-white)",
    sidebarmenu: "var(--clr-grey-3)",
    btnclose: "var(--clr-primary-5)",
    brndark: "var(--clr-primary-8)",
    colorsvgdard: "var(--clr-black)"
    
}

const Theme = {
    dark: darkTheme,
    lg: lgTheme
}

export default Theme